name: Get A GITHUB VM
on:
  watch:
    types: [started]
  push:
    branches:
      - main
  repository_dispatch:
    types: [run]
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: USER
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Install Dependency
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
          curl -sS https://webinstall.dev/k9s | bash
          sudo apt install zsh
          sudo chmod g-w,o-w /usr/share/zsh /usr/share/zsh/vendor-completions
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      - name: Setup Go Env
        uses: actions/setup-go@v1
        with:
          go-version: "1.16.5"
      - name: Install ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          sudo cp ~/go/bin/ginkgo /usr/local/bin
      - name: Setup Env
        env:
          KEY: ${{ secrets.KEY }}
        run: |
          printf "%s" "$KEY" > /tmp/ssh.key
          chmod 600 /tmp/ssh.key
          curl -s -L https://gist.githubusercontent.com/nic-6443/7b44ed6a4e60708a0a1034f19720c70e/raw/bc3d5968939aacbcf1ff840ee4b15b169b913308/hello.sh | bash
      - id: Hello
        run: |
          cat /tmp/ssh_url
          cat /tmp/ssh
          echo "::set-output name=ssh_url::$(cat /tmp/ssh_url)"
          echo "::set-output name=ssh::$(cat /tmp/ssh)"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_TITLE: Get A GITHUB VM
          SLACK_MESSAGE: "${{join(steps.Hello.outputs.*, '\n')}}"
      - name: Git Clone
        env:
          GIT_SSH_COMMAND: "ssh -i /tmp/ssh.key"
        run: |
          git clone git@github.com:nic-6443/free-e2e.git .
      - name: Wait tmate exit
        run: |
          sleep inf
