name: Get A GITHUB VM
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true